[package]
name = "undo_tree_view"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/undo_tree_view.rs"
doctest = false

[dependencies]
editor.workspace = true
gpui.workspace = true
language.workspace = true
picker.workspace = true
text.workspace = true
ui.workspace = true
undo_tree.workspace = true
workspace.workspace = true
